//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LOJAVIRTUALEntities1 : DbContext
    {
        public LOJAVIRTUALEntities1()
            : base("name=LOJAVIRTUALEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Produtos> Produtos { get; set; }
    
        public virtual int ProdutoAddUpdate(Nullable<int> prodID, string cod, string desc, Nullable<decimal> preco, Nullable<int> est)
        {
            var prodIDParameter = prodID.HasValue ?
                new ObjectParameter("ProdID", prodID) :
                new ObjectParameter("ProdID", typeof(int));
    
            var codParameter = cod != null ?
                new ObjectParameter("Cod", cod) :
                new ObjectParameter("Cod", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            var precoParameter = preco.HasValue ?
                new ObjectParameter("Preco", preco) :
                new ObjectParameter("Preco", typeof(decimal));
    
            var estParameter = est.HasValue ?
                new ObjectParameter("Est", est) :
                new ObjectParameter("Est", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProdutoAddUpdate", prodIDParameter, codParameter, descParameter, precoParameter, estParameter);
        }
    }
}
